# -*- coding: utf-8 -*-
"""story_generator_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3WlYpX0ye_xd9ZIWVOJ54R4xPYn-qex
"""


import streamlit as st
from transformers import pipeline, set_seed

# Load the generator
@st.cache_resource
def load_generator():
    return pipeline('text-generation', model='distilgpt2')

generator = load_generator()

# Streamlit UI
st.title("📖 Simple Story Generator")

prompt = st.text_area("Enter a story prompt:", "Once upon a time")

max_length = st.slider("Select story length:", min_value=50, max_value=300, value=100, step=10)
generate_button = st.button("Generate Story")

if generate_button:
    with st.spinner("Generating your story..."):
        set_seed(42)  # for reproducibility
        result = generator(prompt, max_length=max_length, num_return_sequences=1)
        story = result[0]['generated_text']
        st.markdown("### ✨ Generated Story:")
        st.write(story)

